# Generated by Django 6.0.2 on 2026-02-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="inventory_images/"
            ),
        ),
    ]
