# Generated by Django 6.0.2 on 2026-02-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0002_inventoryitem_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockaudit",
            name="reason",
        ),
        migrations.AddField(
            model_name="stockaudit",
            name="action",
            field=models.CharField(default="ACTION", max_length=50),
        ),
        migrations.AddField(
            model_name="stockaudit",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="stockaudit",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="inventory_api.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="stockaudit",
            name="quantity_changed",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
