# Generated by Django 6.0.2 on 2026-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0003_remove_stockaudit_reason_stockaudit_action_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockaudit",
            name="details",
        ),
        migrations.RemoveField(
            model_name="stockaudit",
            name="item",
        ),
        migrations.RemoveField(
            model_name="stockaudit",
            name="quantity_changed",
        ),
        migrations.AddField(
            model_name="stockaudit",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="stockaudit",
            name="fields_changed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockaudit",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="stockaudit",
            name="object_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="stockaudit",
            name="object_type",
            field=models.CharField(default="UNKNOWN", max_length=50),
        ),
        migrations.AddField(
            model_name="stockaudit",
            name="username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="stockaudit",
            name="action",
            field=models.CharField(max_length=20),
        ),
    ]
