# Generated by Django 6.0.2 on 2026-03-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_api",
            "0004_remove_stockaudit_details_remove_stockaudit_item_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
