# Generated by Django 6.0.2 on 2026-03-25 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0005_inventoryitem_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStockSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, unique=True),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
