# Generated by Django 6.0.2 on 2026-03-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="low_stock_threshold",
            field=models.IntegerField(default=5),
        ),
    ]
